version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80" # Map Nginx port 80 to host 5173 for easy access
    depends_on:
      - backend
